###
POST http://localhost:3000/user-pdf
Content-Type: application/json
{
    "email": "testemail2@gmail.com"
}

DELETE http://localhost:3000/user
Content-Type: application/json
{
    "email": "testemail@gmail.com"
}