POST http://localhost:3000/user-pdf
Content-Type: application/json

{
    "email": "testemail@gmail.com"
}

###
POST http://localhost:3000/user
Content-Type: application/json

{
    "email": "testemail@gmail.com",
    "firstName": "Bob",
    "lastName": "Bobinsky",
    "image": "temp.jpg"
}

###
POST http://localhost:3000/sign-in
Content-Type: application/json

{
    "email": "testemail2@gmail.com"
}
